// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvywjcafbbowduxpushr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eXdqY2FmYmJvd2R1eHB1c2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjM2NjcsImV4cCI6MjA3MTAzOTY2N30.GWic2EEB4LwNkvR55NNnuXt0BmZhBB-hcYFrxX6vO3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});